print('Olá, me chamo Thiago Luiz.')
print('Sou formado em Eng. Elétrica.')
print('Atualmente curso Ciência de Dados e Big Data Analytics')
print('Estou subindo alguns arquivos aqui no Github para mostrar meu aprendizado.')
print('Em breve estarei subindo alguns arquivos de projetos que estou trabalhando.')
print('Até breve.')